spring:
  application:
    name: hexagonal
  data:
    mongodb:
      host: 141.148.146.134
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: hexagonal


  kafka:
    bootstrap-servers: 141.148.146.134:29092


chris:
  client:
    address:
      url: http://141.148.146.134:8081/addresses